theme: jekyll-theme-minimal
title: Jin SANO
description: Hello from Tokyo, Japan. I'm Sano, a CS student at Waseda University. Welcome to my web portfolio!
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
logo: bg-sq-dots.png
