---
theme: jekyll-theme-minimal
title: Jin SANO
description: Web Portfolio
---
A banana is an edible fruit – botanically a berry – produced by several kinds
of large herbaceous flowering plants in the genus Musa.
