logo: [./imp_fig.png]
layout: default
theme: jekyll-theme-minimal
title: Jin SANO
description: Web Portfolio
lsi: false
safe: true
source: [https://sano-jin.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
