theme: jekyll-theme-minimal
title: Jin SANO
description: Web Portfolio
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
logo: logo.svg
